version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.12
    steps:
      - checkout
      - run:
          name: Install dependencies in offline mode
          command: yarn install --offline
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push docker image
          command: |
              if [ "${CIRCLE_TAG}" != "" ]; then
                # Install `ibmcloud` CLI and login
                curl -fsSL https://clis.ng.bluemix.net/install/linux | sh

                ibmcloud login \
                  --apikey $CLOUD_API_KEY \
                  -a https://api.ng.bluemix.net \
                  -o 'joshblack@us.ibm.com' \
                  -s dev

                # Install the Container Registry plug-in
                ibmcloud plugin install container-registry -r Bluemix

                # Log the local Docker client in to IBM Cloud Container Registry
                ibmcloud cr login

                docker build -t "registry.ng.bluemix.net/blog-examples/node:${CIRCLE_TAG}" .
                docker push "registry.ng.bluemix.net/blog-examples/node:${CIRCLE_TAG}"
              else
                # Verify in CI that we can build our Dockerfile
                docker build -t "registry.ng.bluemix.net/blog-examples/node:latest" .
              fi
workflows:
  version: 2
  publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
